GPU_ID=$1
CUDA_VISIBLE_DEVICES=${GPU_ID} python train_enc_clevrer.py \
    --load_reference_flag 1 \
    --sim_data_flag 1 \
    --dims 8 \
    --ann_dir /home/zfchen/code/output/causal_output/causal_v15/motions \
    --ref_dir /home/zfchen/code/output/causal_output/reference_v15/motions \
    --ann_dir_val /home/zfchen/code/output/causal_output/causal_v15/motions \
    --ref_dir_val /home/zfchen/code/output/causal_output/reference_v15/motions \
    --train_st_idx 0 \
    --train_ed_idx 8000 \
    --test_st_idx 8000 \
    --test_ed_idx 10000 \
    --val_st_idx  8000 \
    --val_ed_idx 10000 \
    --batch_size 16 \
    --data_noise_aug 1 \
    --data_noise_weight 0.001 \
    --num_workers 2 \
    --mask_aug_prob 0 \
    --save_str v15_mass_ref_aug_noise_001_sim_real \
    --load_reference_flag 1 \
    --mass_only_flag 1 \
    --ref_num_aug 1 \
    --charge_only_flag 0 \
