GPU_ID=$1
CUDA_VISIBLE_DEVICES=${GPU_ID} python train_enc_clevrer.py \
    --train_st_idx 0 \
    --train_ed_idx 4000 \
    --test_st_idx 4000 \
    --test_ed_idx 5000 \
    --train_st_idx2 6000 \
    --train_ed_idx2 10000 \
    --val_st_idx 4000 \
    --val_ed_idx 6000 \
    --dims 11 \
    --sim_data_flag 0 \
    --batch_size 64 \
    --ann_dir /home/zfchen/code/output/render_output_vislab3_bp/v16/render/causal_sim \
    --ref_dir /home/zfchen/code/output/render_output_vislab3_bp/v16/render/reference \
    --track_dir /home/zfchen/code/output/render_output_vislab3_bp/v16/box \
    --ref_track_dir /home/zfchen/code/output/render_output_vislab3_bp/v16/box_reference \
    --ann_dir_val /home/zfchen/code/output/render_output_vislab3_bp/v16/render/causal_sim \
    --ref_dir_val /home/zfchen/code/output/render_output_vislab3_bp/v16/render/reference \
    --track_dir_val /home/zfchen/code/output/render_output_vislab3_bp/v16/box \
    --ref_track_dir_val /home/zfchen/code/output/render_output_vislab3_bp/v16/box_reference \
    --data_noise_aug 1 \
    --data_noise_weight 0.001 \
    --num_workers 0 \
    --mask_aug_prob 0 \
    --save_str v16_mass_noise_001_render_ref \
    --load_reference_flag 1 \
    --mass_only_flag 1 \
    --ref_num_aug 0 \
    --charge_only_flag 0 \
    #--proposal_flag  1 \
    #--ann_dir ../../../output/render_output/ann_v13 \
    #--ref_dir ../../../output/render_output/reference_v13 \
    #--track_dir ../../../output/render_output/box_v13 \
    #--ref_track_dir ../../../output/render_output/box_reference_v13 \
